/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AuraStrategyRegistryV2 {
  export type ReceiptStruct = {
    publisher: AddressLike;
    timestamp: BigNumberish;
    recommendation: string;
    reasoning: string;
    confidenceScore: BigNumberish;
    plainEnglishBrief: string;
    decisionHash: BytesLike;
  };

  export type ReceiptStructOutput = [
    publisher: string,
    timestamp: bigint,
    recommendation: string,
    reasoning: string,
    confidenceScore: bigint,
    plainEnglishBrief: string,
    decisionHash: string
  ] & {
    publisher: string;
    timestamp: bigint;
    recommendation: string;
    reasoning: string;
    confidenceScore: bigint;
    plainEnglishBrief: string;
    decisionHash: string;
  };
}

export interface AuraStrategyRegistryV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "computeDecisionHash"
      | "getReceipt"
      | "getReceiptByPublisherAndHash"
      | "getReceiptCount"
      | "getReceiptIdAt"
      | "hasPublished"
      | "isPublished"
      | "publishReceipt"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecisionReceiptPublished"): EventFragment;

  encodeFunctionData(
    functionFragment: "computeDecisionHash",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptByPublisherAndHash",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptIdAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPublished",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPublished",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishReceipt",
    values: [string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeDecisionHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptByPublisherAndHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptIdAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPublished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishReceipt",
    data: BytesLike
  ): Result;
}

export namespace DecisionReceiptPublishedEvent {
  export type InputTuple = [
    receiptId: BytesLike,
    decisionHash: BytesLike,
    publisher: AddressLike,
    timestamp: BigNumberish,
    confidenceScore: BigNumberish
  ];
  export type OutputTuple = [
    receiptId: string,
    decisionHash: string,
    publisher: string,
    timestamp: bigint,
    confidenceScore: bigint
  ];
  export interface OutputObject {
    receiptId: string;
    decisionHash: string;
    publisher: string;
    timestamp: bigint;
    confidenceScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuraStrategyRegistryV2 extends BaseContract {
  connect(runner?: ContractRunner | null): AuraStrategyRegistryV2;
  waitForDeployment(): Promise<this>;

  interface: AuraStrategyRegistryV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeDecisionHash: TypedContractMethod<
    [
      recommendation: string,
      reasoning: string,
      confidenceScore: BigNumberish,
      plainEnglishBrief: string
    ],
    [string],
    "view"
  >;

  getReceipt: TypedContractMethod<
    [receiptId: BytesLike],
    [AuraStrategyRegistryV2.ReceiptStructOutput],
    "view"
  >;

  getReceiptByPublisherAndHash: TypedContractMethod<
    [publisher: AddressLike, decisionHash: BytesLike],
    [AuraStrategyRegistryV2.ReceiptStructOutput],
    "view"
  >;

  getReceiptCount: TypedContractMethod<[], [bigint], "view">;

  getReceiptIdAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  hasPublished: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  isPublished: TypedContractMethod<
    [publisher: AddressLike, decisionHash: BytesLike],
    [boolean],
    "view"
  >;

  publishReceipt: TypedContractMethod<
    [
      recommendation: string,
      reasoning: string,
      confidenceScore: BigNumberish,
      plainEnglishBrief: string
    ],
    [[string, string] & { receiptId: string; decisionHash: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeDecisionHash"
  ): TypedContractMethod<
    [
      recommendation: string,
      reasoning: string,
      confidenceScore: BigNumberish,
      plainEnglishBrief: string
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [receiptId: BytesLike],
    [AuraStrategyRegistryV2.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptByPublisherAndHash"
  ): TypedContractMethod<
    [publisher: AddressLike, decisionHash: BytesLike],
    [AuraStrategyRegistryV2.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReceiptIdAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hasPublished"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPublished"
  ): TypedContractMethod<
    [publisher: AddressLike, decisionHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishReceipt"
  ): TypedContractMethod<
    [
      recommendation: string,
      reasoning: string,
      confidenceScore: BigNumberish,
      plainEnglishBrief: string
    ],
    [[string, string] & { receiptId: string; decisionHash: string }],
    "nonpayable"
  >;

  getEvent(
    key: "DecisionReceiptPublished"
  ): TypedContractEvent<
    DecisionReceiptPublishedEvent.InputTuple,
    DecisionReceiptPublishedEvent.OutputTuple,
    DecisionReceiptPublishedEvent.OutputObject
  >;

  filters: {
    "DecisionReceiptPublished(bytes32,bytes32,address,uint256,uint8)": TypedContractEvent<
      DecisionReceiptPublishedEvent.InputTuple,
      DecisionReceiptPublishedEvent.OutputTuple,
      DecisionReceiptPublishedEvent.OutputObject
    >;
    DecisionReceiptPublished: TypedContractEvent<
      DecisionReceiptPublishedEvent.InputTuple,
      DecisionReceiptPublishedEvent.OutputTuple,
      DecisionReceiptPublishedEvent.OutputObject
    >;
  };
}
