/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AuraStrategyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getStrategyCount"
      | "owner"
      | "publishStrategy"
      | "strategies"
      | "strategyTimestamps"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StrategyPublished"): EventFragment;

  encodeFunctionData(
    functionFragment: "getStrategyCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publishStrategy",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "strategies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyTimestamps",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getStrategyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strategyTimestamps",
    data: BytesLike
  ): Result;
}

export namespace StrategyPublishedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    publisher: AddressLike,
    recommendation: string,
    reasoning: string,
    confidenceScore: BigNumberish,
    plainEnglishBrief: string
  ];
  export type OutputTuple = [
    timestamp: bigint,
    publisher: string,
    recommendation: string,
    reasoning: string,
    confidenceScore: bigint,
    plainEnglishBrief: string
  ];
  export interface OutputObject {
    timestamp: bigint;
    publisher: string;
    recommendation: string;
    reasoning: string;
    confidenceScore: bigint;
    plainEnglishBrief: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuraStrategyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuraStrategyRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuraStrategyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getStrategyCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  publishStrategy: TypedContractMethod<
    [
      recommendation: string,
      reasoning: string,
      confidenceScore: BigNumberish,
      plainEnglishBrief: string
    ],
    [void],
    "nonpayable"
  >;

  strategies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, string] & {
        timestamp: bigint;
        publisher: string;
        recommendation: string;
        reasoning: string;
        confidenceScore: bigint;
        plainEnglishBrief: string;
      }
    ],
    "view"
  >;

  strategyTimestamps: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getStrategyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishStrategy"
  ): TypedContractMethod<
    [
      recommendation: string,
      reasoning: string,
      confidenceScore: BigNumberish,
      plainEnglishBrief: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "strategies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, string] & {
        timestamp: bigint;
        publisher: string;
        recommendation: string;
        reasoning: string;
        confidenceScore: bigint;
        plainEnglishBrief: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "strategyTimestamps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "StrategyPublished"
  ): TypedContractEvent<
    StrategyPublishedEvent.InputTuple,
    StrategyPublishedEvent.OutputTuple,
    StrategyPublishedEvent.OutputObject
  >;

  filters: {
    "StrategyPublished(uint256,address,string,string,uint8,string)": TypedContractEvent<
      StrategyPublishedEvent.InputTuple,
      StrategyPublishedEvent.OutputTuple,
      StrategyPublishedEvent.OutputObject
    >;
    StrategyPublished: TypedContractEvent<
      StrategyPublishedEvent.InputTuple,
      StrategyPublishedEvent.OutputTuple,
      StrategyPublishedEvent.OutputObject
    >;
  };
}
